version: "3.7"
services:
    server:
        image: padloc/server
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile-server
        networks:
            - ardee_tech_default
        ports:
            - ${PL_SERVER_PORTS}
        volumes:
            - attachments:/attachments
            - logs:/logs
            - data:/data
        restart: unless-stopped
    pwa:
        image: padloc/pwa
        env_file: .env
        build:
            context: .
            dockerfile: Dockerfile-pwa
        volumes:
            - pwa:/pwa
        networks:
            - ardee_tech_default
        ports:
            - ${PL_PWA_PORTS}
        restart: unless-stopped
volumes:
    attachments:
    data:
    logs:
    pwa:
networks:
  ardee_tech_default:
    external: true
